import type { Metadata } from "next";
import "./globals.css";
import RootLayoutComponent from "@/components/layouts/rootLayout";

export const metadata: Metadata = {
  title: "Pixel Tuner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <RootLayoutComponent>
          {children}
        </RootLayoutComponent>
      </body>
    </html>
  );
}
